///////////////////////////////////////////////////////////
//  ChuNhat.cs
//  Implementation of the Class ChuNhat
//  Generated by Enterprise Architect
//  Created on:      02-Mar-2020 9:56:51 AM
//  Original author: Le Tien
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Cau2;
namespace Cau2 {
	public class ChuNhat : Hinh {

		protected double d;
		protected double r;

		public ChuNhat(){

		}

		~ChuNhat(){

		}

		public double chuvi(){

			return 0;
		}

		public double dientich(){

			return 0;
		}

	}//end ChuNhat

}//end namespace Cau2