///////////////////////////////////////////////////////////
//  Diem.cs
//  Implementation of the Class Diem
//  Generated by Enterprise Architect
//  Created on:      02-Mar-2020 9:56:55 AM
//  Original author: Le Tien
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Cau2 {
	public class Diem {

		private double X;
		private double Y;

		public Diem(){

		}

		~Diem(){

		}

	}//end Diem

}//end namespace Cau2