///////////////////////////////////////////////////////////
//  TamGiac.cs
//  Implementation of the Class TamGiac
//  Generated by Enterprise Architect
//  Created on:      02-Mar-2020 9:56:58 AM
//  Original author: Le Tien
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Cau2;
namespace Cau2 {
	public class TamGiac : Hinh {

		protected double a;
		protected double b;
		protected double c;

		public TamGiac(){

		}

		~TamGiac(){

		}

		public double chuvi(){

			return 0;
		}

		public double dientich(){

			return 0;
		}

	}//end TamGiac

}//end namespace Cau2