///////////////////////////////////////////////////////////
//  Vuong.cs
//  Implementation of the Class Vuong
//  Generated by Enterprise Architect
//  Created on:      02-Mar-2020 9:57:00 AM
//  Original author: Le Tien
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Cau2;
namespace Cau2 {
	public class Vuong : ChuNhat {

		public Vuong(){

		}

		~Vuong(){

		}

	}//end Vuong

}//end namespace Cau2