///////////////////////////////////////////////////////////
//  SinhVien.cs
//  Implementation of the Class SinhVien
//  Generated by Enterprise Architect
//  Created on:      02-Mar-2020 1:55:38 PM
//  Original author: Le Tien
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ChoMuonSach;
namespace ChoMuonSach {
	public class SinhVien {

		protected date NamSinh;
		private int SVid;
		private string Ten;
		protected ChoMuonSach.ThuVien ThuVien;
		private string DiaChi;
		public SinhVien(){

		}

		~SinhVien(){

		}

		public int SVid{
			get{
				return SVid;
			}
			set{
				SVid = value;
			}
		}

		public string Ten{
			get{
				return Ten;
			}
			set{
				Ten = value;
			}
		}
		
		public string DiaChi{
			get{
				return DiaChi;
			}
			set{
				DiaChi = value;
			}
		}
		
		public ThuVien ThuVien{
			get{
				return ThuVien;
			}
			set{
				ThuVien = value;
			}
		}

	}//end SinhVien

}//end namespace ChoMuonSach