///////////////////////////////////////////////////////////
//  ThuVien.cs
//  Implementation of the Class ThuVien
//  Generated by Enterprise Architect
//  Created on:      02-Mar-2020 1:55:39 PM
//  Original author: Le Tien
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ChoMuonSach;
namespace ChoMuonSach {
	public class ThuVien {

		private string Id;
		private string Ten;

		public ThuVien(){

		}

		~ThuVien(){

		}

		/// 
		/// <param name="SVid"></param>
		/// <param name="Ten"></param>
		public void ChoSVMuonSach(int SVid, string Ten){

		}

		/// 
		/// <param name="Sachid"></param>
		/// <param name="TenSach"></param>
		public Sach TimSach(int Sachid, string TenSach){

			return null;
		}

	}//end ThuVien

}//end namespace ChoMuonSach